name: dummy_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.5.8
  get_it: ^7.3.0
  dio: ^5.1.1
  dartz: ^0.10.1
  shared_preferences: ^2.1.0
  intl: ^0.18.1
  lottie: ^2.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
