name: dummy_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  dartz: ^0.10.1
  shared_preferences: ^2.1.0
  intl: ^0.18.1
  lottie: ^2.3.2
  scaffold:
    git: git@github.com:wendellrocha/scaffold.git
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
